apiVersion: v1
kind: ConfigMap
metadata:
  name: piyush-demo-1-config
data:
  # Redis configuration (shared with voting01)
  REDIS_HOST: "voting01-dev-redis.2muj25.0001.usw2.cache.amazonaws.com"
  REDIS_PORT: "6379"
  # PostgreSQL configuration (shared with voting01) 
  DATABASE_HOST: "voting01-dev-postgres.chwgk42cofpp.us-west-2.rds.amazonaws.com"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "votes"
  DATABASE_USER: "postgres"
  POSTGRES_HOST: "voting01-dev-postgres.chwgk42cofpp.us-west-2.rds.amazonaws.com"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "votes"
  POSTGRES_USER: "postgres"
  # AWS Secrets Manager ARN for DB credentials
  DATABASE_SECRET_ARN: "arn:aws:secretsmanager:us-west-2:792373136340:secret:rds!db-90524015-d827-4f57-bed1-c14c12675556-pQeqiN"
  # NewRelic configuration
  NEW_RELIC_HOST: "opsera-opsera-newrelic-dev.agent.opsera.dev"
  NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"
  NEW_RELIC_LOG_LEVEL: "info"
  NEW_RELIC_LABELS: "environment:dev;app:piyush-demo-1;team:platform"
  NEW_RELIC_ENVIRONMENT: "dev"
  NEW_RELIC_NO_CONFIG_FILE: "true"
  NEW_RELIC_APPLICATION_LOGGING_ENABLED: "true"
  NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED: "true"
  # Environment
  ENVIRONMENT: "dev"
  LOG_LEVEL: "debug"
