apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-piyush-demo-1-dev

resources:
  - ../../base
  - configmap.yaml
  - serviceaccounts.yaml

commonLabels:
  environment: dev

images:
  - name: vote
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/piyush-demo-1-vote
    newTag: 9d3579c-20260203200038
  - name: result
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/piyush-demo-1-result
    newTag: 9d3579c-20260203200038
  - name: worker
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/piyush-demo-1-worker
    newTag: 9d3579c-20260203200038

patches:
  - target:
      kind: Namespace
      name: opsera-piyush-demo-1-dev
    patch: |-
      - op: replace
        path: /metadata/name
        value: opsera-piyush-demo-1-dev
  - target:
      kind: Ingress
      name: piyush-demo-1
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: opsera-piyush-demo-1-dev.agent.opsera.dev
