apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vote3-qa

resources:
  - ../../base
  - configmap.yaml
  - serviceaccounts.yaml
  - analysis-template.yaml

commonLabels:
  environment: qa

patches:
  - target:
      kind: Ingress
      name: vote3-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: vote-vote3-qa.agent.opsera.dev
      - op: replace
        path: /spec/rules/1/host
        value: result-vote3-qa.agent.opsera.dev

images:
  - name: PLACEHOLDER_VOTE_IMAGE
    newName: PLACEHOLDER_ECR_REGISTRY/vote3-qa-vote
    newTag: 65964d5-20260202190637
  - name: PLACEHOLDER_RESULT_IMAGE
    newName: PLACEHOLDER_ECR_REGISTRY/vote3-qa-result
    newTag: 65964d5-20260202190637
  - name: PLACEHOLDER_WORKER_IMAGE
    newName: PLACEHOLDER_ECR_REGISTRY/vote3-qa-worker
    newTag: 65964d5-20260202190637
