apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vote3-staging

resources:
  - ../../base
  - configmap.yaml
  - serviceaccounts.yaml
  - analysis-template.yaml

commonLabels:
  environment: staging

patches:
  - target:
      kind: Ingress
      name: vote3-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: vote-vote3-staging.agent.opsera.dev
      - op: replace
        path: /spec/rules/1/host
        value: result-vote3-staging.agent.opsera.dev
  # Production-like replicas for staging
  - target:
      kind: Deployment
      name: vote
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: result
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3

images:
  - name: PLACEHOLDER_VOTE_IMAGE
    newName: PLACEHOLDER_ECR_REGISTRY/vote3-staging-vote
    newTag: latest
  - name: PLACEHOLDER_RESULT_IMAGE
    newName: PLACEHOLDER_ECR_REGISTRY/vote3-staging-result
    newTag: latest
  - name: PLACEHOLDER_WORKER_IMAGE
    newName: PLACEHOLDER_ECR_REGISTRY/vote3-staging-worker
    newTag: latest
