# Environment-specific Service Accounts for STAGING with IRSA
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vote
  annotations:
    eks.amazonaws.com/role-arn: "PLACEHOLDER_VOTE_IRSA_ROLE"
  labels:
    app.kubernetes.io/name: vote
    app.kubernetes.io/part-of: vote3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: result
  annotations:
    eks.amazonaws.com/role-arn: "PLACEHOLDER_RESULT_IRSA_ROLE"
  labels:
    app.kubernetes.io/name: result
    app.kubernetes.io/part-of: vote3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
  annotations:
    eks.amazonaws.com/role-arn: "PLACEHOLDER_WORKER_IRSA_ROLE"
  labels:
    app.kubernetes.io/name: worker
    app.kubernetes.io/part-of: vote3
